# Generated by Django 4.0.5 on 2022-06-23 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('descricao', models.TextField()),
                ('publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('disponível', 'Disponível'), ('indisponível', 'Indisponível')], default='indisponível', max_length=12)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['publicacao'],
            },
        ),
    ]
