# Generated by Django 4.0.5 on 2022-06-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='indisponível', max_length=12),
        ),
    ]
